shinhan-hackathon-the-guardians/frontend

package-lock.json, package.json, src/App.tsx, src/components/Header/HeaderBackChatNotify.tsx, src/components/Header/HeaderBackSetting.tsx, src/components/Header/HeaderLogoChatNotify.tsx
- #4 
- 필요한 3가지 헤더 컴포넌트를 구현하였습니다.
- Components 파일 내에 각각의 컴포넌트들을 구현하였습니다.
-
=> #4 [Feat] 헤더 컴포넌트 구현

package-lock.json, package.json, src/App.tsx, src/components/AddGroupMember/InputField.tsx, src/components/AddGroupMember/SelectField.tsx, src/constant/relationship.ts, src/pages/AddGroupMemberPage.tsx, src/routes/router.tsx, tailwind.config.js
- #10
- tailwind color setting
- tailwind.config.js에 color 설정 추가
-
=> #10 [Setting] tailwind color setting

src/components/Question/AnswerButton.tsx, src/components/Question/ProgressBar.tsx, src/components/Question/QuestionInfo.tsx, src/components/Question/ResultModal.tsx, src/constant/common.ts, src/index.css, src/pages/GuardianExamPage.tsx, src/routes/router.tsx, src/utils/data.ts, tailwind.config.js
- #20 
- 가디언 시험 페이지 구현
- 시험 타이머 게이지 구현
- router 추가
- 폰트 오류 수정
- 결과 모달 구현
=> #20 [Feat] 가디언 시험 페이지

package-lock.json, package.json, src/assets/fonts/goorm-font.css, src/hooks/useNavigation.ts, src/index.css, src/pages/LoginPage.tsx, src/pages/MainPage.tsx, src/pages/SignUpPage.tsx, src/routes/router.tsx
=> [Feat] 회원가입 로그인 화면 구현

src/pages/MainPage.tsx
=> [Fix] #27 - 메인 이미지 소스 경로 수정

src/App.tsx, src/components/Question/ResultModal.tsx, src/components/common/InputField.tsx, src/components/common/SelectField.tsx, src/pages/LoginPage.tsx, src/pages/SignUpPage.tsx
- #37 
- 회원가입 및 로그인 폼 디자인 수정
- 회원가입 폼 디자인 수정
- 로그인 폼 디자인 수정
- input 컴포넌트 수정
- select 컴포넌트 수정
=> [Design]: 회원가입 및 로그인 폼 디자인 수정

src/components/Header/HeaderBack.tsx, src/pages/ChatBotPage.tsx, src/pages/MainPage.tsx
=> [Feat] 챗봇 페이지 구현

src/components/common/InputField.tsx, src/components/common/SelectField.tsx, src/pages/SignUpPage.tsx
- #42 
- InputField.tsx의 focus border 변경
- `focus:border-b-2`
-
=> [Feat] #42 InputField focus border 변경

src/components/Question/AnswerButton.tsx, src/components/Question/ResultModal.tsx, src/pages/ChatBotPage.tsx, src/pages/GuardianExamPage.tsx, src/pages/MainPage.tsx, src/pages/QuestionBankPage.tsx
- #48 
- disabled, hover 등 색상 조정
- chat size, main user card 디자인 수정
- AnswerButton 정답 디자인 변경
- MainPage
- QestionBackPage
- GuardianExamPage
- ChatBotPage
- 그 외 컴포넌트
=> [Feat/#48] 전체적인 디자인 수정

.hintrc, src/components/Header/HeaderLogoChatNotify.tsx, src/main.tsx, src/pages/GroupMemberListPage.tsx, src/pages/GuardianExamPage.tsx, src/pages/LoginPage.tsx, src/pages/MainPage.tsx, src/pages/QuestionBankPage.tsx, src/pages/SignUpPage.tsx, src/services/axiosInstance.ts, src/services/groupMemberService.ts, src/services/userAuthService.ts, src/stores/userAuthStore.ts, src/types/User.ts
- #40 
- 로그인/회원가입/로그아웃 연결
- 로그인/회원가입/로그아웃 연결
- user의 값으로 화면 표기들 변경
- 메인 헤더에만 로그아웃 아이콘 추가
=> #40 [Feat] 로그인/회원가입/로그아웃 연결

src/pages/AddGroupMemberPage.tsx, src/pages/GroupMemberListPage.tsx, src/services/groupMemberService.ts
- #50 
- 그룹 관련 api 함수 구현
- 그룹 관련 api 함수 변경 및 추가
- 그룹 목록에서 add함수 구현
- 아직 연동은 안됩니다~
=> #50 [Feat] 그룹 관련 api함수 구현

src/pages/GroupMemberListPage.tsx
- #58 
- 프론트 배포 store 겹침 해결
- userAuthstore 겹침 해결
-
=> [BugFix]: 프론트 배포 store 겹침 해결

src/pages/GuardianExamPage.tsx
- #55 
- import 에러 수정
- import PASS_THRESHOLD 에러 수정
-
=> [BugFix]: import 에러 수정

src/services/questionService.ts
- #55 
- 시험 관련 api 연동
- 잘못된 pass 수정
- response의 body값 체크
- 서포터에서 가디언으로 바뀌는 건 추후에 테스트해야 합니다
- 일단 실패는 잘 뜹니다
=> [Feat]: 시험 관련 api 연동

src/components/GroupMemberList/GroupMemberList.tsx, src/pages/GroupMemberListPage.tsx, src/pages/MainPage.tsx, src/pages/SplashScreen.tsx, src/services/groupMemberService.ts, src/stores/userAuthStore.ts
- #50 
- 유저 로그인 상태 저장
- 로컬 스토리지 store에 추가
- 추후 그룹리스트 연결할 예정
=> #50 [Feat]: 유저 로그인 상태 저장

src/services/userAuthService.ts
- #65 
- 요청 Body의 기존 변수명 "deviceToken" 을 "device_token" 으로 수정
-
-
=> [Fix] 요청 Body 변수명 수정

src/components/GroupMemberList/GroupMemberItem.tsx, src/pages/GroupMemberListPage.tsx, src/services/groupMemberService.ts, src/types/Member.ts, src/types/Response.ts
- #50 
- 그룹 리스트 불러오기
- 그룹 리스트 타입 수정
- 멤버 타입의 level 값 수정
- 멤버아이템의 css 수정
- 그룹원 추가하기는 추후 알림이 모두 되면 이어서 하겠슴당
- 이슈는 닫지 않겠슴당
=> #50 [Feat]: 그룹 리스트 불러오기

package-lock.json, package.json, src/components/Header/HeaderBackChatNotify.tsx, src/components/Header/HeaderLogoChatNotify.tsx, src/components/Question/WarningModal.tsx, src/hooks/useNavigation.ts, src/mock/mock.ts, src/pages/LoginPage.tsx, src/pages/NotificationPage.tsx, src/routes/router.tsx, src/services/notificationService.ts
- #52
- 그룹이 없는 경우) 그룹 초대 승낙
- 가디언의 경우) 멤버들 출금, 이체, 입금 내역 조회
-
-
=> 메인 알림 화면 구현

src/services/axiosInstance.ts
- #82 
- baseURL 수정
- const baseURL = "https://guardian.givendragon.site/api";
-
=> [Fix] baseURL 수정

src/components/Notification/PaymentRequestModal.tsx, src/mock/mock.ts, src/pages/NotificationPage.tsx
=> [Feat] 알림 페이지 예외 처리

src/mock/mock.ts, src/pages/NotificationPage.tsx
- #86 
- Mock 데이터 설정에 오류가 있었습니다.
-
-
=> [Fix] #86 - 빌드 오류 수정

src/App.tsx
=> [Fix]  App 모달 오류 수정

src/components/Question/ResultModal.tsx, src/pages/MainPage.tsx, src/services/userAuthService.ts, src/stores/userAuthStore.ts
- #55 
- 가디언 평가 시 배지 바로 반영
- userAuthStore에 updateLevel 추가
=> [Feat]: 가디언 평가 시 배지 바로 반영

src/pages/AddGroupMemberPage.tsx, src/services/groupMemberService.ts
- #50 
- 그룹원 초대 폼 전화번호 양식 수정
- 그룹원 초대 폼 전화번호 양식 수정
=> [Feat]: 그룹원 초대 폼 전화번호 양식 수정

src/App.tsx
=> [Fix] #101 - case 오류 수정

src/components/Header/HeaderBackChatNotify.tsx, src/components/Header/HeaderBackSetting.tsx, src/pages/MainPage.tsx, src/pages/NotificationPage.tsx, src/services/notificationService.ts
- #96 
- 그룹원 추가 알림 리스트로 변환 및 ui 수정
- 그룹원 추가 알림 리스트로 변환 및 ui 수정
-
=> #96 [Fix] 그룹원 추가 알림 리스트로 변환 및 ui 수정

src/pages/NotificationPage.tsx, src/stores/userAuthStore.ts
- #96 
- 그룹원 초대 승낙 후 메인 업데이트
- 그룹원 초대 승낙 후 메인 업데이트
-
=> #96 [Fix] 그룹원 초대 승낙 후 메인 업데이트

src/App.tsx, src/components/Notification/DepositModal.tsx, src/components/Notification/PaymentFailureModal.tsx, src/components/Notification/PaymentSuccessModal.tsx, src/components/Notification/TransferFailureModal.tsx, src/components/Notification/TransferSuccessModal.tsx, src/components/Notification/WithdrawalFailureModal.tsx, src/components/Notification/WithdrawalSuccessModal.tsx
=> [Feat] #200 모달 전부 완성

src/App.tsx, src/components/Notification/PaymentRequestModal.tsx, src/components/Notification/UnifiedModal.tsx, src/pages/TransactionPage.tsx, src/services/notificationService.ts
=> [Hotfix] 모달 관련

src/components/GroupMemberList/GroupMemberOptions.tsx, src/components/Notification/WithdrawalSuccessModal.tsx
=> [Fix]: 고정 수정

src/components/Notification/DepositModal.tsx
=> [Hotfix] 불필요한 단어 삭제
